Vagrant::Config.run do |config|
  config.vm.define :test_vm do |test_vm|
        test_vm.vm.box = "Ubuntu64"
        test_vm.vm.box_url = "C:\\vagrant\\environments\\boxes\\precise64.box"
		test_vm.vm.share_folder 'v-shared-pkg', '/shared/pkg', '../shared_pkg'
        test_vm.vm.provision :puppet do |puppet|
                puppet.module_path = "~/vagrant/manifests/"
                puppet.module_path = "modules"
                puppet.manifests_path = "manifests"
                puppet.manifest_file  = "test_vm.pp"
        end
  end
end
